### PR TITLE
Implementing New Layout

### PR DESCRIPTION
**Pull request by anaclumos**
We definitely need `title` and `descriptions` in the table!

I see the repository owners are using spreadsheet and special functions to create the markdown table text... But believe me, this new layout will save hours of time of the playground newbies.

### CODE REVIEW

**Comment by Schemetrical** [comment]
Hey, I really like this layout! 

We are currently working to figure out how we best want to manage the repo. Come join the scholars' discord (https://discord.gg/cR2cQ74), I'm `schem` and we can discuss this further.

After we figure out how we want to manage this repo with the team, we can move forward with the new layout. I'll be active after 30 hours (after submission period is over and we all get enough sleep)!

**Comment by Schemetrical** [comment]
Additionally, as you can see, we have a google form set up for the first wave of submissions so that we do not run into merge conflicts. Once we are ready to move forward, we will update this repo and take pull requests from then on!

**Comment by mcichecki** [comment]
What about the country code and emoji flag? It could be quite useful information and can be added as a separate column. What do you think?

**Comment by JordanOsterberg** [comment]
I think adding descriptions might be a little too verbose for this page. The GitHub is meant to be a directory of sorts, rather than a detailed listing of everyone's submission. The external GitHub and YouTube columns are better suited to prove info on projects.

I can get behind titles, though I suppose it's possible that not everyone has a title.

**Comment by omergulen** [comment]
Discord link is expired.

**Comment by omergulen** [comment]
> What about the country code and emoji flag? It could be quite useful information and can be added as a separate column. What do you think?

I think it wouldn't be so good, I mean putting country labels on side of the project names is like classifying people. I would like to see earth emoji on all of the projects tho xd

**Comment by mcichecki** [comment]
@omergulen it might be useful to find someone from your country. Last year I had to go through all ~200 people who submitted they work and check their names to know if someone was coming from Poland. Just an idea though.

**Comment by omergulen** [comment]
> @omergulen it might be useful to find someone from your country. Last year I had to go through all ~200 people who submitted they work and check their names to know if someone was coming from Poland. Just an idea though.

Yeah maybe.

**Comment by omergulen** [comment]
> I think adding descriptions might be a little too verbose for this page. The GitHub is meant to be a directory of sorts, rather than a detailed listing of everyone's submission. The external GitHub and YouTube columns are better suited to prove info on projects.
> 
> I can get behind titles, though I suppose it's possible that not everyone has a title.

I think as people leave blank when they don't have youtube link or github, they can leave blank their titles or descriptions if they wish?

**Comment by ApolloZhu** [comment]
We have to consider the fact that some may have multiple nationalities.

<div style:"display

**Comment by zmknox** [comment]
IMO, descriptions would probably be a bit much for this page. Titles might be worthwhile, though I worry they may get long

**Comment by Schemetrical** [comment]
@mcichecki I think this is what the wwdcscholars website is for, since that has all the acceptances with personal bio and such.

**Comment by mcichecki** [comment]
@Schemetrical fair point

**Comment by omergulen** [comment]
> IMO, descriptions would probably be a bit much for this page. Titles might be worthwhile, though I worry they may get long

We can just put title and description with character limitations, this can easily prevent this.

> @mcichecki I think this is what the wwdcscholars website is for, since that has all the acceptances with personal bio and such.

Also, wwdcscholars website is about acceptances, but here the problem is: When new students come and wanted to look what has been done, I mean I have personally faced a problem, I mean my friend.
He was building a playground for this year but even though he checked most of the projects he didn't see that it was done before because there were no description or title on the projects.

Adding title and description wouldn't be a problem, but not adding is a problem. Thanks, that's my opinion.

**Comment by anaclumos** [comment]
> He was building a playground for this year but even though he checked most of the projects he didn't see that it was done before because there were no description or title on the projects.
> 
> Adding title and description wouldn't be a problem, but not adding is a problem. Thanks, that's my opinion.

Titles and descriptions have more advantages.

* I previously saw a great playground, but couldn’t remember the creator. Titles that concisely describes the content will be far more **memorable** than the creator’s name.
* Prevent similar topics being resubmitted, just like mentioned above
* Get better overview about the contents

Also
* Most of the playgrounds had titles inside the playground. They just did not write it in their repository. Let them write it here, for clearer view.
* Description can have character limits to prevent verbosity

I was always thinking **why isn’t there any descriptions?!** when I was preparing wwdc. I got 20+ tabs opened every time...

After all, this is not only a portfolio site, but also a **great starting point** for applicants. Applicants all have limited time; wouldn’t it be better if they can **save time** otherwise spent opening every repository **only** to check the contents?

**Comment by zmknox** [comment]
I still feel like a title would be enough for that purpose, and not overcrowd the table. I get what you’re saying about being able to go back and find projects.

Also a side note: if you don’t ‘ow whether a project has been done before or not, just build it. You’ll end up building it in your own unique way anyhow.

**Comment by Schemetrical** [comment]
What would you think if instead of \[GitHub\]\(fakeurl\) we could do \[Project Name\]\(fakeurl\)

**Comment by omergulen** [comment]
> > What would you think if instead of [GitHub](fakeurl) we could do [Project Name](fakeurl)
> 
> That would work as well!
> 
> So replying to previous comments:
> 
> The reason why I wanted a short description was that some of the titles might be a bit ambiguous. Like, for example, can you understand the topic if the title says "Smasher" or "Jack on ice"?
> 
> That was why I initially proposed the `description` section as well.
> 
> However, to avoid having multiple columns (and having a short and tall `description` cell → not an ideal view for a long text,) I have used `<br>` tags in my first proposal. That way, we can display much more information **without harming the readability**.
> 
> Also for **information hierarchy**, I suggested using `<strong>` tags or `<sub>` tags to take care of the visual ease. IMO, my first proposal does not harm the **readability** nor **conciseness** of the table... _IMO_.
> 
> Screen Shot 2019-03-28 at 4 58 43 PM

I think this is doable and it should be done ✅

**Comment by JordanOsterberg** [comment]
I’m on board with this iteration of the layout. However, how are people going to be notified? By emailing each person individually? I’d say this might have to be a 2020 thing.

**Comment by omergulen** [comment]
> I’m on board with this iteration of the layout. However, how are people going to be notified? By emailing each person individually? I’d say this might have to be a 2020 thing.

I can write a parser and builder for new syntax and etc. All of us, stated our projects as "submitted" and we can see that 2018 projects have been updated after the announcements. So we can just parse and build them for now, and after that when they come back it can be filled by themselves.

**Comment by zmknox** [comment]
Agree that your layout visualization is nice, we just need to make sure we can implement it for everyone (we have over 100 entries already)

**Comment by Schemetrical** [comment]
As long as it’s optional but encouraged, I hope people will update it when they update their status

**Comment by anaclumos** [comment]
We can make a new `.md` file with this layout and keep the main `README.md` as a legacy option (Just like `iOS`'s 32-bit app support until `iOS11` lol)

Or maybe implement it starting from the next year

We still need to talk about the character limitations and sentence stylings for `description`

**Comment by sahithr03** [comment]
My edit is not saving

**Comment by Nicholas714** [comment]
We can possibly move strictly to a Google Form which will auto format the data, put in character limits, and make it update live without having to make pull requests. 

But instead of having a README.md we would just have a website (since README can’t be live updated) that pulls directly from the Google Form responses instead of the README like the current website does.

**Comment by ApolloZhu** [comment]
Google App Script (i.e. JavaScript) is capable of automating changes upon form submissions.

**Comment by Schemetrical** [comment]
The original intention was to automate this to some extent but it’s hard to come up with the time to build something. 

Definitely something for next year!

**Comment by omergulen** [comment]
Guys, you are just getting away from work, it is not a hard job to do. Please just create a to-do list for this update, such as:

- [x] Editing the .md file
- [ ] Contacting with students who sent their projects
- [ ] Editing stuff on the website

I can do the most of the job if you want, but please consider doing reasonable changes. Otherwise I will create another fork from this repo and try to make it default for attendees. 

I spend time to create a python bot yesterday which parses and builds new theme but nobody even cared about it actually xd I think there are others who can put their effort to make this job better.
Thanks

**Comment by ApolloZhu** [comment]
Agree. Automation can be done next year @Schemetrical , but let’s resolve conflicts in #43 (probably run the python script again? @omergulen ) and get it merged.

**Comment by Schemetrical** [comment]
@omergulen if you want we can talk about it on the discord https://discord.gg/hggERx

If you have the time and you think it would be a better change, please do collaborate with the rest of us to see what can be done better. 

Many of us are university students who have finals coming up and plenty of work. We would appreciate more help if possible.

**Comment by omergulen** [comment]
> @omergulen if you want we can talk about it on the discord https://discord.gg/hggERx
> 
> If you have the time and you think it would be a better change, please do collaborate with the rest of us to see what can be done better.
> 
> Many of us are university students who have finals coming up and plenty of work. We would appreciate more help if possible.

http://prntscr.com/n4t9wx Can't join. Please send it without expiration xd



> Agree. Automation can be done next year @Schemetrical , but let’s resolve conflicts in #43 (probably run the python script again? @omergulen ) and get it merged.

And yeah can do it.

**Comment by omergulen** [comment]
You guys can check #43 again now before adding another merge from another user.

**Comment by Nicholas714** [comment]
@omergulen add my discord nickg#4991 and ill get you added

**Comment by omergulen** [comment]
@Nicholas714 added. Also, you guys can merge new PR #43

**Comment by Schemetrical** [comment]
@omergulen https://discord.gg/n3mt2K this discord invite should work.

**Pull request closed without merging**
