### PR TITLE
New-theme

### PR DESCRIPTION
**Pull request by omergulen**
#2

### CODE REVIEW

**Comment by Schemetrical** [comment]
How would something like the following work for the "Title, Description, Links and Technologies" section:

[One line title of project](http://github.com)
<sub>[YouTube](http://youtube.com), UIKit, ARKit, etc</sub>

This will make the height of rows smaller and more compact.

Also there are missing commas after "YouTube".

**Comment by zmknox** [comment]
> [One line title of project](https://github.com)
> [YouTube](http://youtube.com), UIKit, ARKit, etc

I like this a lot. Will take a lot of work to get titles from everyone, but would for sure be nicer.

**Comment by Schemetrical** [comment]
Also if there is no title the default title should be GitHub (since it links there anyways)

**Comment by omergulen** [comment]
You can help some or wait for me to fix them, both OK.

**Pull request closed without merging**
