### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by aniNatarajan12**
removed self cuz i removed the github repo

### CODE REVIEW

**Comment by zmknox** [comment]
Are you sure you want to remove yourself?

**Comment by aniNatarajan12** [comment]
Yeah because I'm taking down the github repo because I'm gonna upload it to the App Store

**Comment by zmknox** [comment]
Fair enough. You can keep your entry here if you don't have a github repo, just having a youtube link

**Comment by aniNatarajan12** [comment]
nah i think I'm good, thanks for the offer though. the youtube video is still a part of the playlist so thats enough for me

**Comment by zmknox** [comment]
Alright. Thanks!

**Pull request merged**
