### PR TITLE
Add YouTube link

### PR DESCRIPTION
**Pull request by hubertme**

### CODE REVIEW

**Comment by zmknox** [comment]
You've got an extra `[YouTube](` in your parentheses for your video link

**Comment by hubertme** [comment]
Oops... sorry, my bad

**Comment by barbulescualex** [comment]
Hey @zmknox , do you mind adding my video to the youtube playlist as well? https://www.youtube.com/watch?v=7e6X7DzddIQ

Thanks

**Comment by Nicholas714** [comment]
@barbulescualex added

@hubertme commit to this PR with the fix and then we can merge this

**Comment by hubertme** [comment]
@Nicholas714 done!

**Pull request merged**
